### ISSUE TITLE
Project: <short description>The code below uses computer vision to identify hand landmarks of an individual and traces the finger movements which allows the person to draw anything he/she wishes.

### ISSUE THREAD

**Issue by Suyashman** [microsoft/hack-together-teams#106]
### Project name

Virtual Drawing 

### Description

The program allows users to draw and erase on a canvas using hand gestures captured by a camera.
It detects hand landmarks and tracks the position of fingers to enable drawing and erasing functionalities.
Users can change the drawing color, brush size, and switch between drawing and erasing modes.
When the users index finger and middle finger are joined, then only the user can draw whatever he/she wishes.
When the fingers are far apart, drawing is disabled. This allows a person to move his hand from one side to another without having to draw anything.

### Project Repository URL

https://github.com/Suyashman/Drawing-tool.git

### Project video

https://youtu.be/Qp8r1uFnSos

### Team members

Suyash Sunam

**Comment by aycabas** [comment]
Hi @Suyashman, thank you for your project submission. Is this a Teams app? What I understood from the demo is that it's running on desktop at the moment. Please correct me if I'm wrong. Looking forward to hearing from you, thanks!

**Comment by Suyashman** [comment]
Hello sir/ma'am
It is not a teams app.
It is just a program.
This is my first time participating in  a hackathon event. I didn't have
much knowledge on how to make a teams app so i just made a little program
and thought I could submit it.
I wanted to be a part of the event and learn from it ..
Thank you for your time for reviewing my project.

**Comment by aycabas** [comment]
Hi @Suyashman, unfortunately we only accept Teams app submissions at this hackathon. We'll have to tag your submission invalid, however we hope you join us in the next hackathon to learn more about new technologies.

**Comment by Suyashman** [comment]
Thank you for your time and providing feedback. I appreciate your
clarification regarding the submission requirements. Although my project
was invalid, I'm grateful for the opportunity to participate and learn from
the experience. I will definitely consider joining the next hackathon to
explore and develop Teams app-based projects.
Once again, thank you for your time and valuable input.

**Comment by waldekmastykarz** [comment]
Thank you for the kind words, @Suyashman! See you next time! 👋
