### ISSUE TITLE
Project: The notification bot proactively sends messages in Teams channel or group chat or personal chat. You can trigger the notification bot with an HTTP request, such as cards or texts.

### ISSUE THREAD

**Issue by Vaibhavpan02** [microsoft/hack-together-teams#109]
### Project name

Ai-bot

### Description

A common request from companies and organizations considering bots is the ability to be able to notify users on news (e.g. new available features).

This project implements a framework called notifications which enables bot authors to implement a notifications capability, with minimal changes to the actual bot.

It also includes a very simple implementation that illustrates the core concepts with minimal configuration.

This project is written in TypeScript.

### Project Repository URL

https://github.com/Vaibhavpan02/Ai-bot

### Project video

www.youtube.com

### Team members

https://github.com/Vaibhavpan02?tab=repositories

**Comment by aycabas** [comment]
Hi @Vaibhavpan02, I cannot find your details in the registration list. Can you please make sure you register to the hackathon, otherwise you won't be eligible for the digital badge. Registration can be completed from here: https://aka.ms/hack-together-teams/register

**Comment by waldekmastykarz** [comment]
Hey @Vaibhavpan02, it seems like the app you've submitted is not a Teams app. As such, it doesn't meet the hackathon's criteria and we'll have to reject it.
