### ISSUE TITLE
This Project Signifies the Role Of Augmented Reality as well as Provides a 3D View Of the Software 

### ISSUE THREAD

**Issue by Codewithnavy** [microsoft/hack-together-teams#141]
### Project name

AR_Demo

### Description

This is the project related to augmented reality and it adds the value to the teams application by providing the augmented view of the three dimensional component of the objects.
![Uploading Screenshot 2023-04-06 222555.png…]()

### Project Repository URL

https://github.com/Codewithnavy/PropertEaseHactivate

### Project video

https://drive.google.com/file/d/1FjEGqG_Y2VuOQnTad-ZjwmfW8xx7GRqf/view?usp=drive_link

### Team members

https://github.com/rishabh149

**Comment by aycabas** [comment]
Hi @Codewithnavy, thanks for your project submission. Unfortunately, our hackathon submissions were closed on June 15, 11:59 PM PST, so we cannot accept your submission. Hoping to see your projects in the upcoming hackathons! 🙂
