### ISSUE TITLE
Project: Heal360 is a healthcare application integrated into MS Teams, allowing you to seek medical advice and answers to your health-related questions without the need to switch to another platform. It conveniently resides within your Teams app, providing a seamless experience.

### ISSUE THREAD

**Issue by AhmedRaja1** [microsoft/hack-together-teams#70]
### Project name
Heal360

### Description
**What's Heal360?**
_Heal360 is a healthcare application integrated into MS Teams, allowing you to seek medical advice and answers to your health-related questions without the need to switch to another platform. It conveniently resides within your Teams app, providing a seamless experience._

**Target Audience?**
_Targeted at SMEs, Heal360 is the first aid for corporate sector employees._

**Usecases**
1. Be it a minor ache in your chest in working hours.
or
2. If you don't have the time for regular checkups on a quarterly basis, Heal360 is here to help you.

### Project Repository URL
- Main Repo- Here's the main repository containing the code for Teams App ; Heal360.
https://github.com/AhmedRaja1/Heal360

- Secondary Repo- As I have integrated Azure Health Bot into it so, here's my other repository which contains the web application which is consuming Azure Health Bot.
https://github.com/AhmedRaja1/Azure-Health-Bot

### Project video
https://www.youtube.com/watch?v=uTzXiT_LS4c

### Team members
waleedrajay, abd-ar, UETPeshawarGitHubHandles

**Comment by waldekmastykarz** [comment]
Thank you so much for your submission, @AhmedRaja1 and the team! Looking forward to checking it out! Meanwhile, would you be willing to fill in a feedback survey? It would help us improve next time and we'd appreciate it very much: https://aka.ms/hack-together-teams/survey.

**Comment by waldekmastykarz** [comment]
Hey @AhmedRaja1, could it be that you forgot to push your code? Your repo has only 1 commit with the starter code that's created by Teams Toolkit for VSCode?

**Comment by AhmedRaja1** [comment]
> Thank you so much for your submission, @AhmedRaja1 and the team! Looking forward to checking it out! Meanwhile, would you be willing to fill in a feedback survey? It would help us improve next time and we'd appreciate it very much: https://aka.ms/hack-together-teams/survey.

@waldekmastykarz Thanks & I have submitted the feedback form, hope it helps.
![Feedback Form Screenshot](https://github.com/microsoft/hack-together-teams/assets/52793181/fd0bc7c1-450d-4b08-9812-d5235c0f8410 "Feedback Form Screenshot")

**Comment by AhmedRaja1** [comment]
> Hey @AhmedRaja1, could it be that you forgot to push your code? Your repo has only 1 commit with the starter code that's created by Teams Toolkit for VSCode

Esteemed @waldekmastykarz & @aycabas,
Let me clear up the confusion here.

Actually, I have integrated Azure Health Bot in my Teams App within the Tab directly.
I preferred not to put all the code rather I separated the main Teams App code (https://github.com/AhmedRaja1/Heal360) & Azure Health Bot code (https://github.com/AhmedRaja1/Azure-Health-Bot) for better understanding, modularity & performance. 

![Manifest.json file Screenshot](https://github.com/microsoft/hack-together-teams/assets/52793181/f5c8a18e-de55-410b-abd7-dd7bfa3bb60a "Manifest.json file Screenshot")

### Project Repository URL
- Main Repo- Here's the main repository containing the code for Teams App ; Heal360.
https://github.com/AhmedRaja1/Heal360

- Secondary Repo- As I have integrated Azure Health Bot into it so, here's my other repository which contains the web application which is consuming Azure Health Bot.
https://github.com/AhmedRaja1/Azure-Health-Bot

I have updated the above main comment which included all the details.
You folks can look into the app or watch the video for complete elaboration.

I would request you both that please convey the same to jury members too, because I don't want such confusion to be an obstacle to my journey within the hackathon.

If there are still any queries, I would be happy to elaborate on them.

**Comment by aycabas** [comment]
Hi @AhmedRaja1, thanks for all clarifications. One more thing, I cannot find your teammates' details in the registration. Can you please make sure they are all registered with the right github account names: waleedrajay, abd-ar, UETPeshawarGitHubHandles

Otherwise, they won't be eligible for the digital badges.

**Comment by AhmedRaja1** [comment]
@aycabas Thanks for highlighting this matter. 
All mates have filled the form, we thought that filling the form is only mandatory for the team lead.

Also, can you please remove the label "Under Review" from my issue?
I hope that didn't affect us in front of the jury.

**Comment by waldekmastykarz** [comment]
Hey @AhmedRaja1, if I look at the https://github.com/AhmedRaja1/Azure-Health-Bot repo, it seems like it contains code from last year without any changes during the hackathon. As such, we can't accept it to participate in the competition as it wouldn't be fair with other participants. We'll only look at what was at https://github.com/AhmedRaja1/Heal360 at the closing time.

**Comment by AhmedRaja1** [comment]
> Hey @AhmedRaja1, if I look at the https://github.com/AhmedRaja1/Azure-Health-Bot repo, it seems like it contains code from last year without any changes during the hackathon. As such, we can't accept it to participate in the competition as it wouldn't be fair to other participants. We'll only look at what was at https://github.com/AhmedRaja1/Heal360 at closing time.

Dear @waldekmastykarz & @aycabas.
@waldekmastykarz you are right in this statement that the code in the **Azure HealthBot Web App** repository is one year old without any changes during the hackathon.

Dear, I believe you know very well that Azure Health Bot has its own **dedicated portal** as we do have for **Azure Custom Vision**. So, I **even created a new health bot and tweaked it according to my requirements for the hackathon.** 

As far as this Web App Repo is considered, it only uses my **account's Subscription key** and the **Azure Health Bot's API Key**. This web app is just consuming these 2 things. The whole thing is at the backend which is the Healthbot portal. 

So, in a nutshell, even If I change the whole health bot now, this frontend web app will remain the same without any new commits it'll do its job right.

I hope it makes sense now. Just for the sake of better understanding, modularity & performance. I did split the code into 2 different repos, otherwise, it was not that of a heck to do it in a single repo with a lot of senseless commits. I used the best practices.

Also, as far as Hackathon is considered. I have my app in fully working condition as you folks can see by either;

1. Watching the Demo Video on YouTube (https://www.youtube.com/watch?v=uTzXiT_LS4c). On top of it, I do have added screenshots of the app in my repo too.
or 
2. Running the app on your machine.

I hope that will not affect my journey within the hackathon and please convey the same to jury members.
