### ISSUE TITLE
Project: AI Powered chatbot

### ISSUE THREAD

**Issue by kc-clintone** [microsoft/hack-together-teams#93]
### Project name

chatterbot

### Description

A Microsoft Teams chatbot built with OpenAI capabilities. It is an AI-powered conversational agent designed to interact with users in a natural and human-like manner. Leveraging OpenAI's advanced language models, the chatbot can understand and generate text-based responses to user queries, providing helpful information, answering questions, and engaging in conversations on a wide range of topics.

The chatbot utilizes machine learning algorithms and natural language processing techniques to analyze user inputs, comprehend their intent, and generate contextually relevant and coherent responses. It can handle both simple and complex conversations, adapting its responses based on the input received.

### Project Repository URL

https://github.com/kc-clintone/chatterbot-dev

### Project video

https://github.com/microsoft/hack-together-teams/assets/65450355/2b30a9b6-0166-4b0c-b869-6b93ec954091

### Team members

N/A

**Comment by aycabas** [comment]
Hi @kc-clintone, thank you so much for your project submission! We are excited to check it out. Would you be able to provide your project's video before the submission closes, this will help our judges understand your project a little better. Thank you!

**Comment by kc-clintone** [comment]
done👍

**Comment by aycabas** [comment]
Thanks @kc-clintone for your submission and uploading the video 🙂 I'm looking forward to checking the details of your app! We also have a feedback form if you can fill it out, that'd help us improve our hackathon for next time 🙏 https://aka.ms/hack-together-teams/survey
